version: '3.8'

services:
  web:
    build: ./core
    ports:
      - "5000:5000"
    command: flask run --host=0.0.0.0
    networks:
      - shared

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    networks:
      - shared

networks:
  shared:
